Automated Installer & Directory Wrapper
Stalloevan/Dolphin-Taildrop-Plugin pull request #1
Opened 2024-02-16 22:24 UTC by error-try-again

Summary

- Code cleanup, refactoring & organization 
- Automated the procedure so you only need to run a one liner and it installs the plugin
- Integrated a deployment stack for generating a user specific Taildrop service that performs conflict resolution for file sending to the local machine from a remote
- Improved conditional checks, error checking & ping redirection
- Provided a directory wrapper solution so that directories can now be copied over in addition to files as individual archive's

2024-02-17 02:18 UTC, Stalloevan commented
Thanks for the pull. I was looking to implement an automated installer, just haven't had time to get around to it yet. I'm going to review this and get back to you once I'm done.

2024-02-17 02:57 UTC, error-try-again commented
> Thanks for the pull. I was looking to implement an automated installer, just haven't had time to get around to it yet. I'm going to review this and get back to you once I'm done.

No worries. You were most of the way there. It took about an hour and a half to implement and test this morning - if I’ve missed anything just let me know and I’ll make a patch.

2024-02-20 20:27 UTC, Stalloevan requested changes
I left a few comments for review. Other than those, it should be all set to merge.

2024-02-20 20:27 UTC, Stalloevan commented on install.sh
> +  if ! tailscale ping --timeout=1s "${chosen_device}" &>/dev/null; then
The only change I would make is to change this to change this command from `if ! tailscale ping --timeout=1s "${chosen_device}" &>/dev/null; then` to `if ! tailscale ping --c 1 "${chosen_device}" &>/dev/null; then`. When I was working on the code originally, I couldn't use the c  flag to send 1 ping, but it seems to be working now. I only used the timeout flag as a workaround to maintain that 1 ping limit.

2024-02-22 01:07 UTC, error-try-again commented
Awesome - I've updated the ping count limit `tailscale ping -c 1 "${chosen_device}"` and modified the link to direct to the kde website

2024-02-22 14:38 UTC, merged